name: face_detection_tflite_example
description: Example app for face_detection_tflite
publish_to: 'none'
version: 1.0.3+4

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  opencv_dart: 2.1.0
  image_picker: ^1.2.1
  file_selector: ^1.1.0
  file_selector_macos: ^0.9.5
  face_detection_tflite:
    path: ../
  flutter_colorpicker: ^1.1.0
  camera: ^0.12.0
  camera_macos: ^0.0.9
  camera_windows: ^0.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_litert: ^1.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/samples/
    - assets/samples/embedding_test/
    - assets/beach_background.jpg
