name: face_detection_tflite
description: "Advanced face & landmark detection, embedding and segmentation using on-device TFLite models."
version: 4.6.0

repository: https://github.com/hugocornellier/face_detection_tflite
homepage: https://github.com/hugocornellier/face_detection_tflite

topics:
  - tflite
  - face-detection
  - computer-vision
  - flutter-plugin

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^4.7.2
  opencv_dart: ^2.1.0
  tflite_flutter_custom: ^1.2.5
  path: ^1.9.0
  meta: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/face_detection_back.tflite
    - assets/models/face_detection_front.tflite
    - assets/models/face_detection_short_range.tflite
    - assets/models/face_detection_full_range.tflite
    - assets/models/face_detection_full_range_sparse.tflite
    - assets/models/face_landmark.tflite
    - assets/models/iris_landmark.tflite
    - assets/models/mobilefacenet.tflite
    - assets/models/selfie_multiclass.tflite
    - assets/models/selfie_segmenter.tflite
    - assets/models/selfie_segmenter_landscape.tflite
    - assets/bin/libtensorflowlite_c-win.dll
    - assets/bin/libtensorflowlite_c-linux.so

  plugin:
    platforms:
      ios:
        dartPluginClass: FaceDetectionTfliteDart
      android:
        dartPluginClass: FaceDetectionTfliteDart
      macos:
        pluginClass: FaceDetectionTflitePlugin
      windows:
        pluginClass: FaceDetectionTflitePlugin
      linux:
        pluginClass: FaceDetectionTflitePlugin